version: '3'

services:
  # pgadmin
  pgadminapp:
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=bulutbilisimciler
    restart: always

  # PostgreSQL veritabanı
  postgresapp:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres  # Veritabanı adını burada ayarlayabilirsiniz
      POSTGRES_USER: postgres     # Kullanıcı adını burada ayarlayabilirsiniz
      POSTGRES_PASSWORD: postgres  # Parolayı burada ayarlayabilirsiniz
    volumes:
      - /root/workspace/init.sql:/docker-entrypoint-initdb.d/init.sql